### ISSUE TITLE
Customization - New version of plugin does not replace old version if filename is identical

### ISSUE THREAD

**Issue by msoutopico** [kosivantsov/omegat_scripts#10]
**Pre-conditions**

A version _n_ of a plugin is in the local installation and a version _n+1_ is available for download. Accordintly, the remote `version_notes.txt`  has _+1_ version than the local version. E.g.

Latest version in local `version_notes.txt` is: 
```
## Update 51_c0p (2020-07-01)
* Blabla.
```
Local `plugins` folder has: 

  * plugin-omt-package-1.6.1.jar

Latest version in remote `version_notes.txt` is : 
```
## Update 52_c0p (2020-07-03)
* Plugin `plugin-omt-package-1.6.1.jar` available (same name, new functionality).
```

**Expected results**

After the update, the `plugins` folder has (among others): 
  * (new) plugin-omt-package-1.6.1.jar

**Actual results**

After the update, the `plugins` folder has (among others): 
  * (old) plugin-omt-package-1.6.1.jar

**Comment by kosivantsov** [comment]
solved in v.0.4.9
