### ISSUE TITLE
Scripts not updated when customization is two versions old

### ISSUE THREAD

**Issue by msoutopico** [kosivantsov/omegat_scripts#2]
**Preconditions**
1. Some scripts are edited and have a mark like `##OLD##` 

2. Some plugins have old versions (e.g. okapi: 1.5)

3. Latest script version is saved outside of the `scripts` folder:
* @date:    2020-03-06
* @version: 0.4.6
* autoLaunch = false

4. Available customization version is **38_c00**

5. Current version in `version_notes.txt` and `local_version_notes.txt` is **36_c00**

**Steps to reproduce** 
1. In OmegaT, go to Tools > Scripting > File > Open Script and select script 0.4.7 (2019-12-30), run that script.
(2. Insert `https://cat.capstan.be/OmegaT/dev/index.php` if requested)

**Expected results** 
Since there current version is not contiguous to the latest version available (38 - 36 > 1), all config files, scripts and plugins are downloaded and written in `config_dir`. For example, after  the update, 
* file script with `##OLD##` is restored (and that edit is removed) and 
* the old version of the plugin is replaced with the new version

**Actual results**
Plugins are updated but scripts are not. 

![image](https://user-images.githubusercontent.com/3659409/78412002-275b3880-7612-11ea-8260-21d9ba2b1298.png)

**Comment by msoutopico** [comment]
There's no bug. The problem was in the URL being used (and the custom files being downloaded, please ignore).

**Comment by kosivantsov** [comment]
There was a bug which would prevent the update if the older version was of the different order of magnitude. Will be fixed in the next commit.

**Comment by kosivantsov** [comment]
Fixed in v.0.4.7
