### ISSUE TITLE
No prompt about jar files in install_dir/plugins not deleted

### ISSUE THREAD

**Issue by msoutopico** [kosivantsov/omegat_scripts#3]
**Preconditions**
1. Folder `C:\Program Files\OmegaT\plugins` contains some jar files:
* okapiFiltersForOmegaT-1.6-m36-capstan.jar
* plugin-omt-package-1.4.1.jar

2. Installed script `updateConfigBundle.groovy` is the latest version
* @date:    2020-03-06
* @version: 0.4.6
* autoLaunch = false

3. Installed customization version is lower than available version at `https://cat.capstan.be/OmegaT/dev/index.php`

4. File `customisation.properties` has URL `https://cat.capstan.be/OmegaT/dev/index.php`

**Steps to reproduce** 
1. Run `updateConfigBundle.groovy` script.

**Expected results** 
The script deletes the jar files in folder `C:\Program Files\OmegaT\plugins` if it has enough permissions or, if not, the script shows a dialog prompt at the end of the execution asking the user to delete those files manually. 

**Actual results**
No prompt dialog and jar files in  `C:\Program Files\OmegaT\plugins`  not deleted. 
![image](https://user-images.githubusercontent.com/3659409/78413394-82435e80-7617-11ea-9d08-671559827d9c.png)

**Suggestion**
The above dialog could say the following: 

```
               Customization  Update v. XX
                 ====================
 
                 OmegaT will now close.               
                        WARNING:                      
       To avoid conflicts, please delete manually     
all plugin files in C:\Programe Files\OmegaT\plugins.
                        [**OK**]         
              
```

**Comment by kosivantsov** [comment]
Fixed in v.0.4.8
